[package]
name = "eldritch"
version = "0.1.0"
edition = "2021"

[workspace]
default-members = ["apps/editor"]
members = [
    "apps/editor",
    "crates/app"
]

[dependencies]
app = { path = "crates/app" }
