[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.38"
winit = "0.28.1"
log = "0.4"
simple_logger = "4.0.0"
ash = "0.37"
ash-window = "0.12"
raw-window-handle = "0.5"

